# Generated by Django 6.1.1 on 2026-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_image_exercise_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='repetitions',
            field=models.PositiveIntegerField(default=0, help_text='تعداد تکرار؛ اگر تمرین زمانی است صفر بگذارید'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest',
            field=models.PositiveIntegerField(default=0, help_text='زمان استراحت بر حسب ثانیه'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(default=1, help_text='تعداد ست'),
        ),
    ]
